version: "3.9"
services:
  postgresql_db:
    image: postgres:latest
    user: root
    networks:
      - internal_network
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=odoo
      - POSTGRES_PASSWORD=odoo17@2024
      - POSTGRES_DB=postgres
      # - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      # - odoo-postgresql_db-data:/var/lib/postgresql/data/pgdata
      - ./postgresql/data:/var/lib/postgresql/data
    restart: always # run as a service

  odoo:
    container_name: odoo
    image: odoo:latest
    user: root
    volumes:
      - ./odoo/addons:/mnt/extra-addons # contain odoo dev modules
      - ./odoo:/etc/odoo # contain config and log
      - ./odoo/web-data:/var/lib/odoo # contain odoo web data
    networks:
      - internal_network
    ports:
      - "8069:8069" # web
      - "8072:8072" # live chat
    depends_on:
      - postgresql_db
    environment:
      - HOST=postgresql_db
      - USER=odoo
      - PASSWORD=odoo17@2024
  nginx:
    container_name: nginx
    image: nginx:latest
    user: root
    restart: unless-stopped
    networks:
      - internal_network
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/conf:/etc/nginx/conf.d # configuration in default.conf
      - ./nginx/ssl:/etc/nginx/ssl # Secure Sockets Layer (SSL) file: server-sample.crt, server-sample.key
      - ./nginx/html:/usr/share/nginx/html # static html web for example
      - ./nginx/log:/var/log/nginx/
      # - ./certbot/conf:/etc/nginx/ssl
      # - ./certbot/data:/var/www/html
  # certbot:
  #   container_name: certbot
  #   image: certbot/certbot:latest
  #   command: certonly --webroot --webroot-path=/var/www/html --email youremail@mail.com --agree-tos --no-eff-email -d domain.com -d www.domain.com
  #   volumes:
  #     - ./certbot/conf:/etc/letsencrypt
  #     - ./certbot/logs:/var/log/letsencrypt
  #     - ./certbot/data:/var/www/html
networks:
  internal_network:
    driver: bridge
volumes:
  odoo-web-data:
  odoo-db-data:
